title: MRAC - IAAC # your name (or website title) here
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  IaaC's Master in Robotics and Advanced Construction
  <br><br>
  The Master in Robotics and Advanced Construction (MRAC) seeks to train a new generation of interdisciplinary professionals who are capable of facing our growing need for a more sustainable and optimized construction eco-system.
  <br><br>
  <a href="https://iaac.net/mrac">MRAC Website</a> 
  <a href="http://www.iaacblog.com/programs/courses/mrac/2019-2020-mrac/">MRAC Blog</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
